version:"3.8"
services:
app:
build:.
container_name:chat_app
ports:
-"3000:3000"
deponds_on:
-mongo
-redis
environment:
-PORT=3000
-MONGO_URI=mongodb://mongo:27017/chatapp
-JWT_SECRET=Aabc123
-JWT_REFRESH_SECRET=refreshsecret123
-REDIS_HOST= redis
-REDIS_PORT=6379
volums:
-:/app
command:npm start


mongo:
image:mongo
container_name:chatapp_mongo
ports:
-"27017:27017"
volumes:
-mongo_data:/data/db

redis:
image:redis
container_name:chatapp_redis
ports:
-"6379:6379"

volumes:
mongo_data